FROM python:3.9

# set the directory
WORKDIR /api

# copy requirements
COPY ./pyproject.toml ./poetry.lock /api/

# set up poetry
ENV PYTHONPATH=${PYTHONPATH}:${PWD} 
RUN pip3 install poetry
RUN poetry config virtualenvs.create false

# install dependencies
RUN cd /api && poetry install --no-root --only main

# copy backend
COPY . /api 

#Exponsing the port
EXPOSE 80

#build the image
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
