name: check pipeline

on:
  pull_request:
    branches: [main]
    paths:
      - 'app/**'

jobs:
  run-ci:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      PYTHON_VERSION: 3.9
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Detect Changes on Files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            any:
              - '**'
            app:
              - 'app/**'
      - name: Setup Python
        if: steps.changes.outputs.app == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        if: steps.changes.outputs.app == 'true'
        uses: snok/install-poetry@v1

      - name: Configure Poetry and Install Dependencies
        if: steps.changes.outputs.app == 'true'
        run: |
          poetry config --local
          poetry install --no-interaction --no-root
        working-directory: ./app/
      - name: Type Check with mypy
        if: steps.changes.outputs.app == 'true' && github.event_name == 'pull_request'
        run: |
          source .venv/bin/activate
          mypy app
        working-directory: ./

      - name: Test with pytest
        if: steps.changes.outputs.app == 'true'
        run: |
          source .venv/bin/activate
          python -m pytest -v
        working-directory: ./

      - name: Install pytest-cov
        if: steps.changes.outputs.app == 'true'
        run: |
          source .venv/bin/activate
          pip install pytest-cov
        working-directory: ./

      - name: Build coverage file
        if: steps.changes.outputs.app == 'true'
        run: |
          source .venv/bin/activate
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov-config=.coveragerc --cov=app app/tests/ | tee pytest-coverage.txt
        working-directory: ./

      - name: Pytest coverage comment
        if: steps.changes.outputs.app == 'true'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
